GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlYnJvbiIsImlkIjoiNjVjN2UyYWE5Nzc4NzE3MWRiODc4ZjZjIiwiaWF0IjoxNzA4MjAzNDk5fQ.Ih8UXyzvaucTx8O-Wiz9K8y1LwvkysFdZFFp6XWQnts

