GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlYnJvbjEiLCJpZCI6IjY1ZGUwNzViMjExMDYwYzg5MGMzMWI2ZCIsImlhdCI6MTcwOTA0OTcwMX0.W_ibuwXn1FOMEfW62BeO_yxXlWu38EgYgC3Uilgve-s
