POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlYnJvbiIsImlkIjoiNjViZWNkZmYwNmJkNWU0NTk1ZTU4YjMyIiwiaWF0IjoxNzA3NTkyMTIxfQ.6coeXlDuqHTIqdme84O_EGt7YFb1aNMtSjuIqIcCU3g

{
    "content": "lalala 5",
    "userId": "65bed6d7b6e287d050ef593e"
}
